theme: jekyll-theme-cayman
collections:
  ilos:
    output: true
title: "ğŸŒŠ 2023-2024 Y2B PR - Learning Log"
description: Block B - Ocean rendering
student:
  name: Konstantin KozaÄiÅ¡Äe
  number: "222719"